blueprint:
  name: IKEA RODRET Switch - Dual Light Control (Robust)
  description: >
    Control two separate lights with an IKEA RODRET switch using Zigbee2MQTT.
    - Press "on" to toggle Light 1.
    - Press "off" to toggle Light 2.
    - Hold "on" to increase brightness of both lights.
    - Hold "off" to decrease brightness of both lights.
    This robust version uses a separate trigger for each action to ensure reliable operation.
  domain: automation
  input:
    rodret_action_entity:
      name: RODRET Action Entity
      description: "Select the 'action' entity for your RODRET switch (e.g., sensor.bedroom_switch_action)."
      selector:
        entity:
          domain: sensor
    light_1:
      name: Light 1 (On Button)
      description: "The light controlled by the 'on' button press."
      selector:
        entity:
          domain: light
    light_2:
      name: Light 2 (Off Button)
      description: "The light controlled by the 'off' button press."
      selector:
        entity:
          domain: light
    brightness_step:
      name: Brightness Step
      description: "The amount to increase or decrease brightness when holding a button."
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

# A single trigger for any change to the action entity
trigger:
  - platform: state
    entity_id: !input rodret_action_entity
    attribute: action

action:
  - choose:
      # --- Press "On" (Button 1 Short Press) ---
      - conditions:
          - condition: trigger
            to: "on"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_1

      # --- Press "Off" (Button 2 Short Press) ---
      - conditions:
          - condition: trigger
            to: "off"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_2

      # --- Hold "On" (Button 1 Long Press) ---
      - conditions:
          - condition: trigger
            to: "brightness_move_up"
        sequence:
          - repeat:
              until:
                # This condition waits for the "stop" action
                - condition: state
                  entity_id: !input rodret_action_entity
                  attribute: action
                  state: "brightness_stop"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id:
                      - !input light_1
                      - !input light_2
                  data:
                    brightness_step_pct: !input brightness_step
                - delay: 0.5

      # --- Hold "Off" (Button 2 Long Press) ---
      - conditions:
          - condition: trigger
            to: "brightness_move_down"
        sequence:
          - repeat:
              until:
                # This condition waits for the "stop" action
                - condition: state
                  entity_id: !input rodret_action_entity
                  attribute: action
                  state: "brightness_stop"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id:
                      - !input light_1
                      - !input light_2
                  data:
                    brightness_step_pct: -!input brightness_step
                - delay: 0.5

mode: restart
