blueprint:
  name: IKEA RODRET Switch - Dual Light Control (Permissive)
  description: >
    Control two separate lights with an IKEA RODRET switch.
    - Press "on" to toggle Light 1.
    - Press "off" to toggle Light 2.
    - Hold "on" to increase brightness of both lights.
    - Hold "off" to decrease brightness of both lights.
    This version uses a permissive device selector that finds any device with "RODRET" in its name.
  domain: automation
  input:
    rodret_switch:
      name: RODRET Switch
      description: "Select your IKEA RODRET switch. The selector finds any device with 'RODRET' in its name."
      selector:
        device:
          filter:
            - integration: zha
            - integration: mqtt
    light_1:
      name: Light 1 (On Button)
      description: "The light controlled by the 'on' button press."
      selector:
        entity:
          domain: light
    light_2:
      name: Light 2 (Off Button)
      description: "The light controlled by the 'off' button press."
      selector:
        entity:
          domain: light
    brightness_step:
      name: Brightness Step
      description: "The amount to increase or decrease brightness when holding a button."
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

# Universal Trigger for ZHA and Zigbee2MQTT
trigger:
  - platform: device
    device_id: !input rodret_switch
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    id: press_on_zha
  - platform: device
    device_id: !input rodret_switch
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    id: press_off_zha
  - platform: device
    device_id: !input rodret_switch
    domain: zha
    type: remote_button_long_press
    subtype: button_1
    id: hold_on_zha
  - platform: device
    device_id: !input rodret_switch
    domain: zha
    type: remote_button_long_release
    subtype: button_1
    id: release_on_zha
  - platform: device
    device_id: !input rodret_switch
    domain: zha
    type: remote_button_long_press
    subtype: button_2
    id: hold_off_zha
  - platform: device
    device_id: !input rodret_switch
    domain: zha
    type: remote_button_long_release
    subtype: button_2
    id: release_off_zha
  - platform: device
    device_id: !input rodret_switch
    domain: mqtt
    type: button_short_press
    subtype: button_1
    id: press_on_mqtt
  - platform: device
    device_id: !input rodret_switch
    domain: mqtt
    type: button_short_press
    subtype: button_2
    id: press_off_mqtt
  - platform: device
    device_id: !input rodret_switch
    domain: mqtt
    type: button_long_press
    subtype: button_1
    id: hold_on_mqtt
  - platform: device
    device_id: !input rodret_switch
    domain: mqtt
    type: button_long_release
    subtype: button_1
    id: release_on_mqtt
  - platform: device
    device_id: !input rodret_switch
    domain: mqtt
    type: button_long_press
    subtype: button_2
    id: hold_off_mqtt
  - platform: device
    device_id: !input rodret_switch
    domain: mqtt
    type: button_long_release
    subtype: button_2
    id: release_off_mqtt

action:
  - choose:
      # --- ZHA ACTIONS ---
      - conditions:
          - condition: trigger
            id: press_on_zha
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_1
      - conditions:
          - condition: trigger
            id: press_off_zha
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_2
      - conditions:
          - condition: trigger
            id: hold_on_zha
        sequence:
          - repeat:
              until:
                - condition: trigger
                  id:
                    - release_on_zha
              sequence:
                - service: light.turn_on
                  target:
                    entity_id:
                      - !input light_1
                      - !input light_2
                  data:
                    brightness_step_pct: !input brightness_step
                - delay: 0.5
      - conditions:
          - condition: trigger
            id: hold_off_zha
        sequence:
          - repeat:
              until:
                - condition: trigger
                  id:
                    - release_off_zha
              sequence:
                - service: light.turn_on
                  target:
                    entity_id:
                      - !input light_1
                      - !input light_2
                  data:
                    brightness_step_pct: -!input brightness_step
                - delay: 0.5

      # --- Zigbee2MQTT ACTIONS ---
      - conditions:
          - condition: trigger
            id: press_on_mqtt
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_1
      - conditions:
          - condition: trigger
            id: press_off_mqtt
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_2
      - conditions:
          - condition: trigger
            id: hold_on_mqtt
        sequence:
          - repeat:
              until:
                - condition: trigger
                  id:
                    - release_on_mqtt
              sequence:
                - service: light.turn_on
                  target:
                    entity_id:
                      - !input light_1
                      - !input light_2
                  data:
                    brightness_step_pct: !input brightness_step
                - delay: 0.5
      - conditions:
          - condition: trigger
            id: hold_off_mqtt
        sequence:
          - repeat:
              until:
                - condition: trigger
                  id:
                    - release_off_mqtt
              sequence:
                - service: light.turn_on
                  target:
                    entity_id:
                      - !input light_1
                      - !input light_2
                  data:
                    brightness_step_pct: -!input brightness_step
                - delay: 0.5

mode: restart
