blueprint:
  name: IKEA RODRET 2-Gang Zigbee2MQTT Switch - Dual Light Control
  description: >
    Control two separate lights with an IKEA RODRET switch using Zigbee2MQTT.
    - Press "on" to toggle Light 1.
    - Press "off" to toggle Light 2.
    - Hold "on" to increase brightness of both lights.
    - Hold "off" to decrease brightness of both lights.
    This blueprint bypasses the device selector and uses the MQTT topic directly for maximum compatibility.
  domain: automation
  input:
    mqtt_topic:
      name: RODRET Switch MQTT Topic
      description: >
        The base MQTT topic for your RODRET switch (e.g., 'zigbee2mqtt/Bedroom Switch').
        Find this in the Zigbee2MQTT integration settings.
      default: ""
    light_1:
      name: Light 1 (On Button)
      description: "The light controlled by the 'on' button press."
      selector:
        entity:
          domain: light
    light_2:
      name: Light 2 (Off Button)
      description: "The light controlled by the 'off' button press."
      selector:
        entity:
          domain: light
    brightness_step:
      name: Brightness Step
      description: "The amount to increase or decrease brightness when holding a button."
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

# Trigger directly on the MQTT topic for the specified actions
trigger:
  - platform: mqtt
    topic: !input mqtt_topic
    id: press_on
    value_template: "{{ value_json.action == 'on' }}"
  - platform: mqtt
    topic: !input mqtt_topic
    id: press_off
    value_template: "{{ value_json.action == 'off' }}"
  - platform: mqtt
    topic: !input mqtt_topic
    id: brightness_up_start
    value_template: "{{ value_json.action == 'brightness_move_up' }}"
  - platform: mqtt
    topic: !input mqtt_topic
    id: brightness_down_start
    value_template: "{{ value_json.action == 'brightness_move_down' }}"
  - platform: mqtt
    topic: !input mqtt_topic
    id: brightness_stop
    value_template: "{{ value_json.action == 'brightness_stop' }}"

condition: []

action:
  - choose:
      # --- Toggle Light 1 (On Button) ---
      - conditions:
          - condition: trigger
            id: press_on
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_1

      # --- Toggle Light 2 (Off Button) ---
      - conditions:
          - condition: trigger
            id: press_off
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_2

      # --- Brightness Up Loop ---
      - conditions:
          - condition: trigger
            id: brightness_up_start
        sequence:
          - repeat:
              until:
                - condition: trigger
                  id: brightness_stop
              sequence:
                - service: light.turn_on
                  target:
                    entity_id:
                      - !input light_1
                      - !input light_2
                  data:
                    brightness_step_pct: !input brightness_step
                - delay: 0.5

      # --- Brightness Down Loop ---
      - conditions:
          - condition: trigger
            id: brightness_down_start
        sequence:
          - repeat:
              until:
                - condition: trigger
                  id: brightness_stop
              sequence:
                - service: light.turn_on
                  target:
                    entity_id:
                      - !input light_1
                      - !input light_2
                  data:
                    brightness_step_pct: -!input brightness_step
                - delay: 0.5

mode: restart
